volumes:
  pg_data_production:
  static_volume:
  media_volume:
services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data/
  backend:
    image: lasellar/epatazhnost_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media/
    depends_on:
      - db
  #bot:
    #image: lasellar/epatazhnost_bot
    #env_file: .env
    #depends_on:
      #- db
  frontend:
    image: lasellar/epatazhnost_frontend
    env_file: .env
    volumes:
      - static_volume:/frontend_static
    command: cp -r /app/build/. /frontend_static/
  gateway:
    image: lasellar/epatazhnost_gateway
    env_file: .env
    volumes:
      - static_volume:/backend_static/
      - media_volume:/app/media/
    ports:
      - 8000:80

networks:
  default:
    name: bridge_network
    driver: bridge