# Generated by Django 4.2.17 on 2025-01-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsize',
            name='is_in_stock',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
