# Generated by Django 4.2.17 on 2025-01-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_itemsize_is_in_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='imageitem',
            options={'verbose_name': 'Вещь-доп.фото', 'verbose_name_plural': 'Вещь-доп.фото'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Мерч', 'verbose_name_plural': 'Мерч'},
        ),
        migrations.AlterModelOptions(
            name='itemsize',
            options={'verbose_name': 'Вещь-размер', 'verbose_name_plural': 'Вещь-размер'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Размер', 'verbose_name_plural': 'Размеры'},
        ),
        migrations.AlterField(
            model_name='itemsize',
            name='is_in_stock',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
