# Generated by Django 4.2.17 on 2025-01-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0003_alter_category_options_alter_imageitem_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='itemsize',
            constraint=models.UniqueConstraint(fields=('item', 'size'), name='unique-item-size'),
        ),
    ]
