# Generated by Django 4.2.17 on 2025-01-22 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0004_itemsize_unique_item_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='itemcategory', to='api_v1.category'),
            preserve_default=False,
        ),
    ]
