# Generated by Django 4.2.17 on 2025-01-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0005_item_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to='gigs_images')),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=5)),
                ('place', models.CharField(max_length=128)),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Концерт',
                'verbose_name_plural': 'Концерты',
            },
        ),
        migrations.AlterModelOptions(
            name='imageitem',
            options={'verbose_name': 'фото', 'verbose_name_plural': 'фото'},
        ),
        migrations.AlterModelOptions(
            name='itemsize',
            options={'verbose_name': 'размер', 'verbose_name_plural': 'размер'},
        ),
    ]
