# Generated by Django 4.2.17 on 2025-01-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0006_gig_alter_imageitem_options_alter_itemsize_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=2399),
            preserve_default=False,
        ),
    ]
