# Generated by Django 4.2.17 on 2025-01-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0007_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='tickets_url',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
