# Generated by Django 4.2.17 on 2025-01-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0008_gig_tickets_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='is_published',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
