# Generated by Django 4.2.17 on 2025-01-22 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0010_shoppingcart_shoppingcart_unique_user_item'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='unique-user-item',
        ),
    ]
