# Generated by Django 4.2.17 on 2025-01-22 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0012_alter_item_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsize',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemsize', to='api_v1.size'),
        ),
    ]
