# Generated by Django 4.2.17 on 2025-01-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0013_alter_itemsize_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sizes',
            field=models.ManyToManyField(related_name='itemsizes', through='api_v1.ItemSize', to='api_v1.size'),
        ),
    ]
