# Generated by Django 4.2.17 on 2025-01-29 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0016_promocode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemorder', to='api_v1.item')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie', models.CharField(max_length=60)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('third_name', models.CharField(max_length=64)),
                ('telegram', models.CharField(max_length=1024)),
                ('sdek', models.CharField(max_length=1024)),
            ],
            options={
                'verbose_name': 'Инфо о пользователе',
                'verbose_name_plural': 'Инфо о пользователях',
            },
        ),
        migrations.AddField(
            model_name='promocode',
            name='discount',
            field=models.IntegerField(default=10, verbose_name='скидка в %'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(related_name='orderitems', through='api_v1.ItemOrder', to='api_v1.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1.userinfo')),
            ],
        ),
        migrations.AddField(
            model_name='itemorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemorder', to='api_v1.order'),
        ),
    ]
