# Generated by Django 4.2.17 on 2025-02-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0017_itemorder_userinfo_promocode_discount_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPagePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='main_page_images')),
                ('is_published', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'verbose_name': 'Фото с главной страницы',
                'verbose_name_plural': 'фото с главной страницы',
            },
        ),
    ]
