# Generated by Django 4.2.17 on 2025-02-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0018_mainpagephoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=14)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Бот',
            },
        ),
    ]
