# Generated by Django 4.2.17 on 2025-02-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0019_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(help_text='если нужно сделать рассылку, надо перечислить id пользователей через запятую с пробелом', max_length=14)),
                ('message', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.DeleteModel(
            name='Bot',
        ),
    ]
