# Generated by Django 4.2.17 on 2025-02-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0020_message_delete_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chat_id',
            field=models.TextField(help_text='если нужно сделать рассылку, надо перечислить id пользователей через запятую с пробелом'),
        ),
    ]
