# Generated by Django 4.2.17 on 2025-02-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0021_alter_message_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='discount',
            field=models.FloatField(verbose_name='скидка в %'),
        ),
    ]
