# Generated by Django 4.2.17 on 2025-02-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0022_alter_promocode_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='telegram',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
