# Generated by Django 4.2.17 on 2025-02-15 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0024_alter_userinfo_cookie_alter_userinfo_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='extra_images')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='extra_images',
            field=models.ManyToManyField(related_name='itemextraimages', through='api_v1.ImageItem', to='api_v1.image'),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageitem', to='api_v1.image'),
        ),
    ]
