# Generated by Django 4.2.17 on 2025-02-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0025_image_item_extra_images_alter_imageitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='extra_images',
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='image',
            field=models.ImageField(upload_to='items_images'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
