openapi: 3.0.2
info:
  title: 'epatazhnost'
  version: '1'
paths:
  /api_v1/concerts/:
    get:
      operationId: Список концертов
      description: ''
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ConcertList'
                description: 'Список объектов текущей страницы'
          description: ''
      tags:
        - Концерты
  /api_v1/concerts/{id}/:
    get:
      operationId: Получение концерта
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          description: 'Уникальный идентификатор концерта'
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConcertList'
          description: ''
      tags:
        - Концерты
  /api_v1/shop/:
    get:
      operationId: Список Товаров
      description: 'Доступна фильтрация по категориям'
      parameters:
        - name: category
          required: false
          in: query
          description: 'Показывать только товары с выбранной категорией'

          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: 'Успешный ответ'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ShopList'
      tags:
        - Магазин
  /api_v1/shop/{id}:
    get:
      operationId: Получение товара
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          description: "Уникальный идентификатор товара"
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShopList'
          description: ''
      tags:
        - Магазин
  /api_v1/shop/{id}/shopping-cart/:
    post:
      operationId: Добавить товар в список покупок
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          description: "Уникальный идентификатор товара"
          schema:
            type: string
      responses:
        '201':
          description: 'Товар успешно добавлен в список покупок'
        '400':
          description: 'Ошибка удаления из списка покупок'
        '404':
          description: 'Товар не найден'
      tags:
        - Магазин

    delete:
      operationId: Удалить товар из списка покупок
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          description: "Уникальный идентификатор товара"
          schema:
            type: string
      responses:
        '204':
          description: 'Товар успешно удален из списка покупок'
        '400':
          description: 'Ошибка удаления из списка покупок'
        '404':
          description: 'Товар не найден'
      tags:
        - Магазин

components:
  schemas:
    ConcertList:
      description: 'Концерт'
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        city:
          type: string
          maxLength: 64
          example: "Москва"
          readOnly: true
        image:
          type: string
          format: uri
          description: 'Ссылка на обложку'
          example: 'http://example.org/media/gigs_images/moscow.png'
          readOnly: true
        date:
          type: string
          maxLength: 10
          example: '23.01'
          readOnly: true
        time:
          type: string
          maxLength: 5
          example: '01:04'
          readOnly: true
        place:
          type: string
          maxLength: 128
          example: 'TAGO))) MAGO)))'
          readOnly: true
        price:
          type: integer
          readOnly: true
          example: 500
        tickets_url:
          type: string
          description: 'Ссылка на сайт, где продаются билеты'
          example: "https://vk.com/artist/epatazhnost"
          readOnly: true
        is_published:
          type: boolean
          readOnly: true
          description: "Отображается ли на странице"
          example: false

    ShopList:
      type: object
      description: 'Товар'
      properties:
        id:
          type: integer
          readOnly: true
          description: 'Уникальный id'
        is_published:
          type: boolean
          readOnly: true
          description: 'Отображается ли на странице'
          example: false
        name:
          type: string
          readOnly: true
          example: "Футболка обычная"
        price:
          type: integer
          readOnly: true
          example: 1599
        description:
          type: string
          readOnly: true
          example: "Описаниефутболки 123"
        sizes:
          type: array
          description: 'Список размеров'
          items:
            example:
              name: "L"
              is_in_stock: false
            type: object
            properties:
              name:
                type: string
              is_in_stock:
                type: boolean
            required:
              - name
              - is_in_stock
        main_image:
          type: string
          example: "/media/items_images/unnamed.png"
          readOnly: true
        attachments:
          type: array
          description: 'Список uri картинок'
          items:
            example:
              "/media/items_images/big_765604.jpg"
            type: string





